/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsDate, IsOptional, IsString, ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { PassengerCreateNestedManyWithoutFlightsInput } from "./PassengerCreateNestedManyWithoutFlightsInput";
import { StopCreateNestedManyWithoutFlightsInput } from "./StopCreateNestedManyWithoutFlightsInput";

@InputType()
class FlightCreateInput {
  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  arrivalTime?: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  departureTime?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  destination?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  flightNumber?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  origin?: string | null;

  @ApiProperty({
    required: false,
    type: () => PassengerCreateNestedManyWithoutFlightsInput,
  })
  @ValidateNested()
  @Type(() => PassengerCreateNestedManyWithoutFlightsInput)
  @IsOptional()
  @Field(() => PassengerCreateNestedManyWithoutFlightsInput, {
    nullable: true,
  })
  passengers?: PassengerCreateNestedManyWithoutFlightsInput;

  @ApiProperty({
    required: false,
    type: () => StopCreateNestedManyWithoutFlightsInput,
  })
  @ValidateNested()
  @Type(() => StopCreateNestedManyWithoutFlightsInput)
  @IsOptional()
  @Field(() => StopCreateNestedManyWithoutFlightsInput, {
    nullable: true,
  })
  stops?: StopCreateNestedManyWithoutFlightsInput;
}

export { FlightCreateInput as FlightCreateInput };
